# Generated by Django 3.0.2 on 2020-03-17 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('moviedesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=255)),
                ('genredesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'movietypes',
                'db_table': 'movietype',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatername', models.CharField(max_length=255)),
                ('theaterurl', models.URLField(blank=True, null=True)),
                ('theaterscreens', models.SmallIntegerField(blank=True, null=True)),
                ('theateraddress', models.TextField(blank=True, max_length=255, null=True)),
                ('theatercity', models.CharField(max_length=64)),
                ('theaterstate', models.CharField(max_length=2)),
                ('theaterzip', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'theaters',
                'db_table': 'theater',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revtitle', models.CharField(max_length=255)),
                ('revdate', models.DateField()),
                ('rating', models.CharField(blank=True, choices=[('0', '0 Stars'), ('.5', '1/2 Star'), ('1', '1 Star'), ('1.5', '1.5 Stars'), ('2', '2 Stars'), ('2.5', '2.5 Stars'), ('3', '3 Stars'), ('3.5', '3.5 Stars'), ('4', '4 Stars'), ('4.5', '4.5 Stars'), ('5', '5 Stars')], max_length=4, null=True)),
                ('revdesc', models.TextField()),
                ('movietitle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieReviews.Movie')),
                ('theatertitle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieReviews.Theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genrename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieReviews.MovieType'),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieReviews.Review'),
        ),
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieReviews.Theater'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
