# Generated by Django 3.0.2 on 2020-03-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genrename',
            new_name='movietype',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='stars',
            new_name='rating',
        ),
    ]
