# Generated by Django 3.0.2 on 2020-03-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0003_auto_20200318_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movietype',
            new_name='genrename',
        ),
    ]
