# Generated by Django 3.0.2 on 2020-03-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0004_auto_20200318_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genrename',
            new_name='movietype',
        ),
    ]
